services:
  - type: web
    name: studyshelf-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://kanapuramrakshitha2005_db_user:Rakshitha2005@cluster0.ybvekn0.mongodb.net/studyshelf?appName=Cluster0
      - key: PORT
        value: 5000